format="""
[░▒▓](#a3aed2)\
$username\
[](fg:#A3AED2 bg:#002366)\
$directory\
[](fg:#002366 bg:#394260)\
$git_branch\
$git_status\
[](#394260)\
$java\
$nodejs\
$rust\
$c\
$python\
\n $character
"""


[username]
show_always = true 
style_user = " fg:#000000 bg:#A3AED2"
style_root = "bg:#346995"
format = '[ $user ]($style)'
disabled = false


[directory]
style = "fg:#e3e5e5 bg:#002366"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = " fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = " fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = " fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol =""
style = " fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[c]
symbol =" "
style = " fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

# [c++]
# symbol = " "
# style = "bg:#FFFFFF"
# format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

